[package]
name = "rustlib_add"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustlib_add"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
clap = { version = "3.0", features = ["derive"] }
